# Generated by Django 3.2.5 on 2021-08-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Титульная страница'},
        ),
    ]
