# Generated by Django 3.2.5 on 2021-08-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailitemheader',
            name='parent',
        ),
        migrations.DeleteModel(
            name='EmailItemFooter',
        ),
        migrations.DeleteModel(
            name='EmailItemHeader',
        ),
    ]
