# Generated by Django 3.2.5 on 2021-08-02 10:13

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('site_settings', '0002_auto_20210802_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ForeignKey(blank=True, help_text='Рекомендуемые размеры изображения 260x260', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_color',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black')], default='#FFFFFFFF', help_text='Цвет интерфейса и вкладки браузера Android, фона плитки в Windows', max_length=18, verbose_name='Цветовая тема'),
        ),
    ]
