# Generated by Django 3.2.5 on 2021-08-02 15:09

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_alter_sitesettings_theme_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слоган вашей компании'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='theme_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Цвет интерфейса и вкладки браузера Android, фона плитки в Windows', max_length=18, null=True, verbose_name='Цветовая тема'),
        ),
    ]
