# Generated by Django 3.2.5 on 2021-08-02 16:18

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_auto_20210802_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Карта'),
        ),
    ]
