# Generated by Django 3.2.5 on 2021-08-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_sitesettings_map_embed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='map_embed',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adress_exp',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
