# Generated by Django 3.2.5 on 2021-08-02 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_auto_20210802_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='adress_exp',
        ),
    ]
