# Generated by Django 3.2.5 on 2021-08-12 08:38

from django.db import migrations
import project_name.streams.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inner_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpage',
            name='content',
            field=wagtail.core.fields.StreamField([('richtext', project_name.streams.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
