# Generated by Django 3.2.5 on 2021-08-12 15:05

from django.db import migrations
import project_name.streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('inner_pages', '0002_textpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpage',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.StructBlock([('heading_text', wagtail.core.blocks.CharBlock(max_length=250, required=True)), ('heading_size', wagtail.core.blocks.ChoiceBlock(choices=[('H2', 'H2'), ('H3', 'H3'), ('H4', 'H4')]))])), ('richtext', project_name.streams.blocks.RichTextBlock()), ('quote', wagtail.core.blocks.StructBlock([('quote_text', wagtail.core.blocks.BlockQuoteBlock()), ('quote_author', wagtail.core.blocks.CharBlock(max_length=200, required=True))])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(max_length=250, required=True))])), ('embed', wagtail.core.blocks.StructBlock([('embed', wagtail.embeds.blocks.EmbedBlock()), ('embed_position', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Слева'), ('center', 'В центре'), ('right', 'Справа'), ('full_width', 'Справа')]))])), ('slider', wagtail.core.blocks.StructBlock([('images', wagtail.core.blocks.ListBlock(child_block=wagtail.core.blocks.StructBlock(
                [('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение')), ('caption', wagtail.core.blocks.CharBlock(label='Подпись изображения', max_length=250, required=True))]), label='Изображения в слайдере'))])), ('gallery', wagtail.core.blocks.StructBlock([('images', wagtail.core.blocks.ListBlock(child_block=wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение')), ('caption', wagtail.core.blocks.CharBlock(label='Подпись изображения', max_length=250, required=True))]), label='Изображения в галлерее'))])), ('table', project_name.streams.blocks.TableBlock()), ('buttons', wagtail.core.blocks.StructBlock([('buttons_text', wagtail.core.blocks.ListBlock(child_block=wagtail.core.blocks.CharBlock(label='Подпись кнопки', max_length=250, required=True), label='Подписи кнопок'))])), ('media_and_text', project_name.streams.blocks.ImageAndTextBlock()), ('file', project_name.streams.blocks.FileBlock()), ('audio', project_name.streams.blocks.MediaBlock())], blank=True, null=True),
        ),
    ]
